### ISSUE TITLE
can't install without already having torch because of single source version

### ISSUE THREAD

**Issue by cjekel** [LLNL/spdlayers#1]
The single source versioning is preventing the install of `spdlayers` if torch is not already installed.

```
  Downloading spdlayers-0.0.1.tar.gz (5.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/jekel1/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zp/5vhkq5hx4xzggt_c9byjb1rm00108b/T/pip-install-23eut413/spdlayers/setup.py'"'"'; __file__='"'"'/private/var/folders/zp/5vhkq5hx4xzggt_c9byjb1rm00108b/T/pip-install-23eut413/spdlayers/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zp/5vhkq5hx4xzggt_c9byjb1rm00108b/T/pip-pip-egg-info-214x75bw
         cwd: /private/var/folders/zp/5vhkq5hx4xzggt_c9byjb1rm00108b/T/pip-install-23eut413/spdlayers/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zp/5vhkq5hx4xzggt_c9byjb1rm00108b/T/pip-install-23eut413/spdlayers/setup.py", line 7, in <module>
        import spdlayers.version as spdlayers
      File "/private/var/folders/zp/5vhkq5hx4xzggt_c9byjb1rm00108b/T/pip-install-23eut413/spdlayers/spdlayers/__init__.py", line 1, in <module>
        from .layers import Cholesky  # noqa F401
      File "/private/var/folders/zp/5vhkq5hx4xzggt_c9byjb1rm00108b/T/pip-install-23eut413/spdlayers/spdlayers/layers.py", line 5, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by cjekel** [comment]
fixed in https://github.com/LLNL/spdlayers/commit/dc401420cd26c8d2418c75a9d8db591039e63faf
